player.onChat(tp Agent, function () {
    agent.teleportToPlayer()
})
player.onChat(skola, function () {
    agent.teleportToPlayer()
    agent.setSlot(1)
    agent.setAssist(PLACE_ON_MOVE, true)
    agent.setAssist(DESTROY_OBSTACLES, true)
    agent.setItem(YELLOW_TERRACOTTA, 200, 1)
    agent.setItem(ORANGE_TERRACOTTA, 200, 2)
    for (let index = 0; index  12; index++) {
        for (let index = 0; index  2; index++) {
            agent.setSlot(1)
            agent.move(FORWARD, 15)
            agent.turn(LEFT_TURN)
            agent.move(FORWARD, 7)
            agent.turn(RIGHT_TURN)
            agent.move(FORWARD, 4)
            agent.turn(RIGHT_TURN)
            agent.setSlot(2)
            agent.move(FORWARD, 5)
            agent.turn(LEFT_TURN)
            agent.move(FORWARD, 8)
            agent.turn(LEFT_TURN)
            agent.move(FORWARD, 7)
            agent.setSlot(1)
            agent.turn(RIGHT_TURN)
            agent.move(FORWARD, 8)
            agent.turn(LEFT_TURN)
            agent.move(FORWARD, 48)
            agent.turn(LEFT_TURN)
            agent.move(FORWARD, 8)
            agent.turn(RIGHT_TURN)
            agent.setSlot(2)
            agent.move(FORWARD, 7)
            agent.turn(LEFT_TURN)
            agent.move(FORWARD, 8)
            agent.turn(LEFT_TURN)
            agent.move(FORWARD, 5)
            agent.setSlot(1)
            agent.turn(RIGHT_TURN)
            agent.move(FORWARD, 4)
            agent.turn(RIGHT_TURN)
            agent.move(FORWARD, 7)
            agent.turn(LEFT_TURN)
            agent.move(FORWARD, 15)
        }
        agent.move(UP, 1)
    }
})
